### ISSUE TITLE
Need a QR code for the Website URL

### ISSUE THREAD

**Issue by kmurthyhegde** [HavyaKanvas/ItsSandhyaTime#41]
https://ItsSandhyaTime.in

We need a high-res QR Code for this (png file). When the user uses a scanner on this QR code, it should take to this website on the browser.

**Comment by BhargavHegde07** [comment]
![It's Sandhya time](https://github.com/user-attachments/assets/e316b09b-7b8b-405c-9428-3be4b46f1b82)
